[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "build"
  node_version = "18.17.0"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
for = "/*"
  [headers.values]
  Access-Control-Allow-Origin = "*"
